apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: greeting-deployment
spec:
  selector:
    matchLabels:
      app: greeting
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: nvakulenko/greeting:1.0-SNAPSHOT
          ports:
            - containerPort: 80