apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: greeting-deployment
spec:
  selector:
    matchLabels:
      app: greeting
  replicas: 1 # tells deployment to run n pod(s) matching the template
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: nvakulenko/greeting:1.1-SNAPSHOT
          ports:
            - containerPort: 8080
        - name: mongo
          image: mongo:3.4.1
          ports:
            - containerPort: 27017